"""Portfolio Report — writes a markdown summary of all missions to disk."""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from pathlib import Path

from agent.mos.mission_state import Mission, MissionStatus
from agent.mos.mission_analytics import MissionAnalytics

logger = logging.getLogger(__name__)


class PortfolioReport:

    def __init__(self, project_root: str | Path = ".") -> None:
        self._root     = Path(project_root).resolve()
        self._out_dir  = self._root / ".kryth" / "mos" / "reports"
        self._out_dir.mkdir(parents=True, exist_ok=True)

    def generate(
        self,
        portfolio: dict[str, Mission],
        analytics: MissionAnalytics,
        label: str = "",
    ) -> str:
        """Write report. Returns path."""
        now = datetime.now(timezone.utc)
        slug = label or now.strftime("%Y%m%d_%H%M%S")
        path = self._out_dir / f"portfolio_{slug}.md"
        content = self._render(portfolio, analytics, now)
        path.write_text(content, encoding="utf-8")
        logger.info("Portfolio report: %s", path)
        return str(path)

    # ── Render ────────────────────────────────────────────────────────

    def _render(
        self,
        portfolio: dict[str, Mission],
        analytics: MissionAnalytics,
        now: datetime,
    ) -> str:
        missions = sorted(portfolio.values(), key=lambda m: m.created_at)
        summary  = analytics.summary()

        def count(s): return sum(1 for m in missions if m.status == s)

        lines = [
            "# KRYTH Mission OS — Portfolio Report",
            "",
            f"**Generated:** {now.isoformat()[:19]}  "
            f"**Total Missions:** {len(missions)}",
            "",
            "---",
            "",
            "## Portfolio Summary",
            "",
            f"| Status | Count |",
            f"|--------|-------|",
            f"| Running   | {count(MissionStatus.RUNNING)} |",
            f"| Queued    | {count(MissionStatus.QUEUED)} |",
            f"| Paused    | {count(MissionStatus.PAUSED)} |",
            f"| Blocked   | {count(MissionStatus.BLOCKED)} |",
            f"| Completed | {count(MissionStatus.COMPLETED)} |",
            f"| Failed    | {count(MissionStatus.FAILED)} |",
            f"| Archived  | {count(MissionStatus.ARCHIVED)} |",
            "",
            "## Analytics",
            "",
            f"| Metric | Value |",
            f"|--------|-------|",
            f"| Success Rate | {summary.get('success_rate', 0)*100:.1f}% |",
            f"| Avg Elapsed | {summary.get('avg_elapsed_s', 0):.1f}s |",
            f"| Avg Worker Utilization | {summary.get('avg_worker_util_pct', 0):.1f}% |",
            f"| Avg Token Utilization | {summary.get('avg_token_util_pct', 0):.1f}% |",
            "",
            "---",
            "",
            "## Mission Details",
            "",
        ]

        for m in missions:
            status_tag = f"[{m.status.value.upper()}]"
            lines += [
                f"### {status_tag} {m.name or m.id}",
                "",
                f"**ID:** `{m.id}`  **Priority:** {m.priority.value}  "
                f"**Elapsed:** {m.elapsed_s():.1f}s",
                "",
                f"**Goal:** {m.goal}",
                "",
                f"| Metric | Value |",
                f"|--------|-------|",
                f"| Actions Total | {m.metrics.actions_total} |",
                f"| Actions Done | {m.metrics.actions_done} |",
                f"| Actions Failed | {m.metrics.actions_failed} |",
                f"| Progress | {m.metrics.progress_pct:.1f}% |",
                f"| Replans | {m.metrics.replan_count} |",
                f"| Confidence | {m.metrics.confidence:.0%} |",
                f"| Risk | {m.metrics.risk_level} |",
                f"| Token % | {m.budget.token_pct:.1f}% |",
            ]
            if m.result_summary:
                lines += [f"", f"**Result:** {m.result_summary}"]
            if m.status_reason:
                lines += [f"**Reason:** {m.status_reason}"]
            if m.depends_on:
                lines += [f"**Depends on:** {', '.join(m.depends_on)}"]
            lines += [""]

        lines += [
            "---",
            "",
            "*Generated by KRYTH Mission Operating System.*",
            "*No production changes were made automatically by this report.*",
            "",
        ]
        return "\n".join(lines)
