export const tokens = {
  bg:        "#0B0B0C",
  surface:   "#111214",
  panel:     "#151618",
  panelHover:"#1A1B1E",
  border:    "#25272B",
  borderSoft:"#1E1F23",
  text:      "#F5F5F5",
  muted:     "#8A8F98",
  dim:       "#5A5F67",
  accent:    "#60A5FA",
  success:   "#4ADE80",
  warning:   "#FACC15",
  danger:    "#F87171",
} as const;

export type ThemeToken = keyof typeof tokens;

export const monacoTheme = {
  base: "vs-dark" as const,
  inherit: true,
  rules: [
    { token: "",                  foreground: "F5F5F5" },
    { token: "comment",           foreground: "5A5F67", fontStyle: "italic" },
    { token: "keyword",           foreground: "F87171" },
    { token: "keyword.control",   foreground: "F87171" },
    { token: "string",            foreground: "4ADE80" },
    { token: "string.escape",     foreground: "60A5FA" },
    { token: "number",            foreground: "60A5FA" },
    { token: "regexp",            foreground: "4ADE80" },
    { token: "type",              foreground: "FACC15" },
    { token: "type.identifier",   foreground: "FACC15" },
    { token: "class",             foreground: "FACC15" },
    { token: "function",          foreground: "60A5FA" },
    { token: "variable",          foreground: "F5F5F5" },
    { token: "variable.language", foreground: "60A5FA" },
    { token: "constant",          foreground: "60A5FA" },
    { token: "operator",          foreground: "8A8F98" },
    { token: "delimiter",         foreground: "5A5F67" },
    { token: "tag",               foreground: "4ADE80" },
    { token: "attribute.name",    foreground: "60A5FA" },
    { token: "attribute.value",   foreground: "4ADE80" },
    { token: "decorator",         foreground: "60A5FA" },
    { token: "namespace",         foreground: "FACC15" },
  ],
  colors: {
    "editor.background":                     "#0B0B0C",
    "editor.foreground":                     "#F5F5F5",
    "editor.lineHighlightBackground":        "#151618",
    "editor.selectionBackground":            "#60A5FA30",
    "editor.inactiveSelectionBackground":    "#60A5FA15",
    "editor.findMatchBackground":            "#FACC1540",
    "editor.findMatchHighlightBackground":   "#FACC1520",
    "editorCursor.foreground":               "#60A5FA",
    "editorLineNumber.foreground":           "#3A3D43",
    "editorLineNumber.activeForeground":     "#5A5F67",
    "editorWidget.background":               "#151618",
    "editorWidget.border":                   "#25272B",
    "editorSuggestWidget.background":        "#151618",
    "editorSuggestWidget.border":            "#25272B",
    "editorSuggestWidget.selectedBackground":"#1A1B1E",
    "editorSuggestWidget.highlightForeground":"#60A5FA",
    "editorGutter.background":               "#0B0B0C",
    "editorIndentGuide.background1":          "#1E1F23",
    "editorIndentGuide.activeBackground1":    "#25272B",
    "editor.wordHighlightBackground":        "#60A5FA10",
    "editor.wordHighlightStrongBackground":  "#60A5FA20",
    "scrollbar.shadow":                      "#00000030",
    "scrollbarSlider.background":            "#25272B80",
    "scrollbarSlider.hoverBackground":       "#3A3D43A0",
    "scrollbarSlider.activeBackground":      "#5A5F67",
    "minimap.background":                    "#0B0B0C",
    "diffEditor.insertedTextBackground":     "#4ADE8020",
    "diffEditor.removedTextBackground":      "#F8717120",
    "diffEditor.insertedLineBackground":     "#4ADE8010",
    "diffEditor.removedLineBackground":      "#F8717110",
    "panel.background":                      "#111214",
    "panelTitle.activeBorder":               "#60A5FA",
    "focusBorder":                           "#60A5FA",
    "input.background":                      "#111214",
    "input.border":                          "#25272B",
    "input.foreground":                      "#F5F5F5",
    "input.placeholderForeground":           "#5A5F67",
    "list.hoverBackground":                  "#1A1B1E",
    "list.activeSelectionBackground":        "#1A1B1E",
    "list.activeSelectionForeground":        "#F5F5F5",
    "sideBar.background":                    "#111214",
    "activityBar.background":                "#0B0B0C",
    "titleBar.activeBackground":             "#0B0B0C",
    "statusBar.background":                  "#0B0B0C",
  },
};
