export const tokens = {
  bg:        "#0A0A0A",
  surface:   "#111111",
  surface2:  "#171717",
  surface3:  "#1F1F1F",
  active:    "#27272A",
  border:    "rgba(255,255,255,0.05)",
  text:      "#FAFAFA",
  text2:     "#A1A1AA",
  muted:     "#71717A",
  subtle:    "#52525B",
  accent:    "#DFFF00",
  accentFg:  "#000000",
  success:   "#22C55E",
  warning:   "#F59E0B",
  error:     "#EF4444",
  info:      "#3B82F6",
} as const;

export type ThemeToken = keyof typeof tokens;

/** Monaco dark theme (Codex-style) */
export const monacoTheme = {
  base: "vs-dark" as const,
  inherit: true,
  rules: [
    { token: "",                  foreground: "FAFAFA" },
    { token: "comment",           foreground: "52525B", fontStyle: "italic" },
    { token: "keyword",           foreground: "A1A1AA", fontStyle: "bold" },
    { token: "keyword.control",   foreground: "A1A1AA" },
    { token: "string",            foreground: "86EFAC" },
    { token: "string.escape",     foreground: "6EE7B7" },
    { token: "number",            foreground: "FCA5A5" },
    { token: "regexp",            foreground: "FCA5A5" },
    { token: "type",              foreground: "93C5FD" },
    { token: "type.identifier",   foreground: "93C5FD" },
    { token: "class",             foreground: "C4B5FD" },
    { token: "function",          foreground: "C4B5FD" },
    { token: "variable",          foreground: "FAFAFA" },
    { token: "variable.language", foreground: "A1A1AA" },
    { token: "constant",          foreground: "FDE68A" },
    { token: "operator",          foreground: "71717A" },
    { token: "delimiter",         foreground: "52525B" },
    { token: "tag",               foreground: "FCA5A5" },
    { token: "attribute.name",    foreground: "FDE68A" },
    { token: "attribute.value",   foreground: "86EFAC" },
    { token: "decorator",         foreground: "6EE7B7" },
    { token: "namespace",         foreground: "93C5FD" },
  ],
  colors: {
    "editor.background":                     "#0D0D0D",
    "editor.foreground":                     "#FAFAFA",
    "editor.lineHighlightBackground":        "#FFFFFF06",
    "editor.selectionBackground":            "#DFFF0030",
    "editor.inactiveSelectionBackground":    "#FFFFFF0A",
    "editor.findMatchBackground":            "#DFFF0050",
    "editor.findMatchHighlightBackground":   "#DFFF0025",
    "editorCursor.foreground":               "#FAFAFA",
    "editorLineNumber.foreground":           "#27272A",
    "editorLineNumber.activeForeground":     "#52525B",
    "editorWidget.background":               "#111111",
    "editorWidget.border":                   "#FFFFFF0D",
    "editorSuggestWidget.background":        "#171717",
    "editorSuggestWidget.border":            "#FFFFFF0D",
    "editorSuggestWidget.selectedBackground": "#1F1F1F",
    "editorSuggestWidget.highlightForeground": "#FAFAFA",
    "editorGutter.background":               "#0D0D0D",
    "editorIndentGuide.background1":          "#1F1F1F",
    "editorIndentGuide.activeBackground1":    "#27272A",
    "editor.wordHighlightBackground":        "#FFFFFF08",
    "editor.wordHighlightStrongBackground":  "#DFFF0020",
    "scrollbar.shadow":                      "#00000000",
    "scrollbarSlider.background":            "#FFFFFF0A",
    "scrollbarSlider.hoverBackground":       "#FFFFFF14",
    "scrollbarSlider.activeBackground":      "#FFFFFF1F",
    "minimap.background":                    "#0A0A0A",
    "diffEditor.insertedTextBackground":     "#22C55E20",
    "diffEditor.removedTextBackground":      "#EF444420",
    "diffEditor.insertedLineBackground":     "#22C55E10",
    "diffEditor.removedLineBackground":      "#EF444410",
    "panel.background":                      "#111111",
    "panelTitle.activeBorder":               "#DFFF00",
    "focusBorder":                           "#FFFFFF1F",
    "input.background":                      "#111111",
    "input.border":                          "#FFFFFF0D",
    "input.foreground":                      "#FAFAFA",
    "input.placeholderForeground":           "#52525B",
    "list.hoverBackground":                  "#1F1F1F",
    "list.activeSelectionBackground":        "#27272A",
    "list.activeSelectionForeground":        "#FAFAFA",
    "sideBar.background":                    "#111111",
    "activityBar.background":                "#111111",
    "titleBar.activeBackground":             "#0D0D0D",
    "statusBar.background":                  "#0A0A0A",
  },
};
