"""Dynamic Team Generator — creates engineering roles from a TaskDAG.

Agent roles are generated by an LLM that reads the actual task nodes,
user intent, and repo profile. This produces roles tailored to the specific
request rather than a fixed set of templates.

Fallback: if LLM is unavailable, _generate_fixed_team() maps capabilities
to the original 11-role template set.
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from typing import Dict, List, Optional

from agent.orchestration.task_dag import TaskDAG, TaskNode


@dataclass
class OwnedScope:
    """Resources an agent exclusively owns during execution."""
    files: List[str] = field(default_factory=list)
    symbols: List[str] = field(default_factory=list)
    directories: List[str] = field(default_factory=list)
    ports: List[int] = field(default_factory=list)


@dataclass
class AgentRole:
    id: str
    role: str
    mission: str
    owns: OwnedScope = field(default_factory=OwnedScope)
    task_node_ids: List[str] = field(default_factory=list)
    dependencies: List[str] = field(default_factory=list)
    validation_rules: List[str] = field(default_factory=list)
    recovery_rules: List[str] = field(default_factory=list)
    tools: List[str] = field(default_factory=list)
    max_turns: int = 80


@dataclass
class TeamPlan:
    agents: List[AgentRole]
    complexity: float
    risk_assessment: str
    estimated_total_turns: int
    estimated_total_tokens: int
    parallel_benefit: float
    parallel_cost: float
    recommended_strategy: str
    reasoning: str
    layer_count: int = 1


def team_from_contract(team_contract, user_input: str = "", *,
                       strategy: str = "parallel") -> TeamPlan:
    """Build a TeamPlan DIRECTLY from an approved MissionTeamContract.

    This is the source-of-truth path: the teams (and their owned tasks) shown in
    the Mission Execution Preview become the EXACT agents spawned — no LLM
    re-generation, no template fallback, no substitution. ``team_contract`` has
    ``.teams`` = {team label: [task names]} (a dict-like is also accepted).
    """
    teams = (team_contract.teams if hasattr(team_contract, "teams")
             else dict(team_contract or {}))
    # Priority order: foundational domains first so dependent work starts on
    # warm outputs (and the concurrency cap spends early slots on what unblocks
    # the most downstream work). Lower number = sooner.
    _PRIORITY = {
        "infrastructure": 0, "database": 1, "auth": 2, "security": 3,
        "backend": 4, "payments": 5, "frontend": 6, "testing": 7,
        "documentation": 8, "deploy": 9, "deployment": 9,
    }

    def _prio(label: str) -> int:
        key = str(label).lower().replace(" team", "").strip()
        return _PRIORITY.get(key, 5)

    ordered = sorted(teams.items(), key=lambda kv: (_prio(kv[0]), str(kv[0])))
    agents: List[AgentRole] = []
    for label, tasks in ordered:
        aid = re.sub(r"[^a-z0-9]+", "_", str(label).lower()).strip("_") or "agent"
        tasks = list(tasks or [])
        mission = (f"{label}: own and complete {', '.join(tasks)}" if tasks
                   else f"{label}: complete the {label} work for: {user_input[:80]}")
        agents.append(AgentRole(
            id=aid, role=str(label), mission=mission,
            task_node_ids=list(tasks),          # the previewed tasks = owned tasks
            dependencies=[],                      # contract teams start together
            max_turns=80,
        ))
    n = max(1, len(agents))
    return TeamPlan(
        agents=agents, complexity=float(n), risk_assessment="from-contract",
        estimated_total_turns=n * 80, estimated_total_tokens=n * 80 * 2000,
        parallel_benefit=float(n), parallel_cost=1.0,
        recommended_strategy=strategy, reasoning="Built from approved Mission Execution Preview contract",
        layer_count=1,
    )


# ---------------------------------------------------------------------------
# LLM-generated dynamic team
# ---------------------------------------------------------------------------

_TEAM_SYSTEM = """You are an engineering team architect. Your job: read the task and generate exactly 4 specialized agents that divide the work into 4 non-overlapping parallel slices.

═══ NON-NEGOTIABLE RULES ═══
1. ALWAYS generate exactly 4 agents — no more, no fewer.
2. Every agent MUST have "depends_on": [] — all 4 start at the same time.
3. Each agent owns distinct, non-overlapping files/directories.
4. Missions are specific to the actual task — never generic filler.
5. max_turns: 40–100 per agent based on scope.

═══ HOW TO SPLIT WORK ═══
Divide by vertical slice (each agent owns a full vertical of the system):
  - Slice A: data layer  (db models, schema, migrations, seeds)
  - Slice B: logic layer (services, business logic, API routes, handlers)
  - Slice C: UI layer    (components, pages, styles, state management)
  - Slice D: infra layer (tests, CI, Docker, docs, config)

For tasks without clear layers, split by feature domain:
  - Slice A: feature core (main business logic, data structures)
  - Slice B: feature API  (endpoints, serializers, validators)
  - Slice C: feature UI   (pages, forms, visualizations)
  - Slice D: feature ops  (tests, error handling, logging, monitoring)

For single-layer tasks (e.g. pure refactor, pure testing), split by module/directory:
  - Slice A: first 25% of files by path
  - Slice B: next 25%
  - Slice C: next 25%
  - Slice D: last 25% + integration

═══ EXAMPLES ═══

REQUEST: "Build a full-stack e-commerce app with auth, products, cart and checkout"
OUTPUT:
[
  {"id":"data","role":"Data & Auth Engineer","mission":"Create database schema for users/products/orders, implement auth middleware with JWT, seed data","depends_on":[],"owned_dirs":["src/db","src/auth","migrations"],"max_turns":70},
  {"id":"api","role":"API Engineer","mission":"Build REST endpoints for products, cart, checkout; wire up Stripe payments and order processing","depends_on":[],"owned_dirs":["src/api","src/services","src/middleware"],"max_turns":90},
  {"id":"ui","role":"Frontend Engineer","mission":"Build product listing, cart sidebar, checkout flow, and auth pages with React and Tailwind","depends_on":[],"owned_dirs":["src/components","src/pages","src/hooks"],"max_turns":90},
  {"id":"ops","role":"DevOps & QA Engineer","mission":"Write unit+integration tests, set up Dockerfile, GitHub Actions CI, and environment configs","depends_on":[],"owned_dirs":["tests","docker",".github","docs"],"max_turns":50}
]

REQUEST: "Refactor the Python backend to use async SQLAlchemy and fix N+1 query issues"
OUTPUT:
[
  {"id":"models","role":"ORM Migration Engineer","mission":"Convert all SQLAlchemy models to async, update Base classes, fix relationship loading strategies to eliminate N+1","depends_on":[],"owned_dirs":["app/models","app/database"],"max_turns":70},
  {"id":"services","role":"Service Layer Engineer","mission":"Refactor service functions to async/await, replace synchronous queries with optimized async batch queries","depends_on":[],"owned_dirs":["app/services","app/repositories"],"max_turns":80},
  {"id":"routes","role":"Route Handler Engineer","mission":"Update all FastAPI route handlers and dependencies to async, fix session lifecycle management","depends_on":[],"owned_dirs":["app/routers","app/dependencies"],"max_turns":70},
  {"id":"tests","role":"Test & Validation Engineer","mission":"Update all tests to use pytest-asyncio, add query-count assertions, run and fix failing tests","depends_on":[],"owned_dirs":["tests","scripts"],"max_turns":60}
]

REQUEST: "Add real-time notifications with WebSockets to the existing chat app"
OUTPUT:
[
  {"id":"ws-server","role":"WebSocket Server Engineer","mission":"Implement WebSocket connection manager, message broadcaster, and room/channel logic in the backend","depends_on":[],"owned_dirs":["backend/websockets","backend/channels"],"max_turns":80},
  {"id":"ws-client","role":"WebSocket Client Engineer","mission":"Build React hooks for WebSocket connections, implement reconnection logic and message queue on the frontend","depends_on":[],"owned_dirs":["frontend/hooks","frontend/context","frontend/websocket"],"max_turns":70},
  {"id":"notifications","role":"Notification UI Engineer","mission":"Build notification bell component, notification list, toast system, and unread badge with real-time updates","depends_on":[],"owned_dirs":["frontend/components/notifications","frontend/stores"],"max_turns":70},
  {"id":"persistence","role":"Persistence & Testing Engineer","mission":"Add notification model and DB schema, write integration tests for WebSocket flows, add e2e test","depends_on":[],"owned_dirs":["backend/models","tests","migrations"],"max_turns":50}
]

═══ JSON SCHEMA ═══
Each agent object:
  "id": string (kebab-case, unique)
  "role": string (specific job title, not "Engineer" alone)
  "mission": string (one sentence, task-specific, action-oriented)
  "depends_on": [] (always empty array — mandatory)
  "owned_dirs": [string] (directories this agent exclusively writes to)
  "max_turns": number (40–100)

Return ONLY the JSON array. No explanation, no markdown fences."""


def _llm_generate_team(
    dag: TaskDAG,
    user_input: str,
    repo_summary: str,
) -> Optional[List[dict]]:
    """Ask the planner model to generate a dynamic team. Returns raw agent dicts or None."""
    try:
        from agent.llm import _get_client, PLANNER_MODEL

        dag_summary = json.dumps([
            {"id": n.id, "name": n.name, "description": n.description,
             "capabilities": n.capabilities_required,
             "dirs": n.affected_dirs, "files": n.affected_files[:4]}
            for n in dag.nodes.values()
        ], separators=(",", ":"))

        prompt = (
            f"Task: {user_input[:800]}\n\n"
            f"Repository context: {repo_summary[:800]}\n\n"
            f"Work items: {dag_summary[:1500]}\n\n"
            "Generate the 4-agent parallel team:"
        )
        try:
            from agent.model_router import TaskRole, pick_model_for_role
            _team_model = pick_model_for_role(TaskRole.PLANNING)
        except Exception:
            _team_model = PLANNER_MODEL
        client = _get_client()
        resp = client.chat.completions.create(
            model=_team_model,
            messages=[
                {"role": "system", "content": _TEAM_SYSTEM},
                {"role": "user", "content": prompt},
            ],
            temperature=0,
            max_tokens=2000,
            timeout=10,
        )
        raw = (resp.choices[0].message.content or "").strip()
        raw = re.sub(r"^```[a-z]*\n?", "", raw).rstrip("`").strip()
        start = raw.find("[")
        end = raw.rfind("]")
        if start < 0 or end <= start:
            return None
        agents = json.loads(raw[start:end + 1])
        if isinstance(agents, list) and agents:
            return agents
    except Exception:
        pass
    return None


def _parse_llm_agents(raw_agents: List[dict], dag: TaskDAG) -> Optional[List[AgentRole]]:
    """Validate and convert raw LLM agent dicts to AgentRole objects."""
    known_node_ids = set(dag.nodes.keys())
    seen_ids: set = set()
    roles: list[AgentRole] = []

    for raw in raw_agents[:4]:
        aid = str(raw.get("id", "")).strip().replace(" ", "-")
        if not aid or aid in seen_ids:
            continue
        seen_ids.add(aid)

        try:
            turns = max(15, min(120, int(raw.get("max_turns", 60))))
        except (TypeError, ValueError):
            turns = 60

        task_ids = [t for t in (raw.get("task_node_ids") or []) if t in known_node_ids]
        deps = [str(d).strip() for d in (raw.get("depends_on") or []) if str(d).strip()]

        owned = OwnedScope(
            directories=list(raw.get("owned_dirs") or []),
            files=list(raw.get("owned_files") or []),
        )

        # Inherit validation/recovery from owned task nodes
        validation: list[str] = []
        recovery: list[str] = []
        for nid in task_ids:
            node = dag.nodes.get(nid)
            if node:
                validation.extend(node.validation)
                if node.rollback_strategy:
                    recovery.append(node.rollback_strategy)

        roles.append(AgentRole(
            id=aid,
            role=str(raw.get("role", aid)),
            mission=str(raw.get("mission", f"Complete {aid} tasks")),
            owns=owned,
            task_node_ids=task_ids,
            dependencies=deps,
            validation_rules=validation,
            recovery_rules=recovery,
            max_turns=turns,
        ))

    if not roles:
        return None

    # Validate deps reference known agent ids
    valid_aids = {r.id for r in roles}
    for r in roles:
        r.dependencies = [d for d in r.dependencies if d in valid_aids]

    return roles


# ---------------------------------------------------------------------------
# Public builder
# ---------------------------------------------------------------------------

def generate_team(dag: TaskDAG, user_input: str = "", repo_profile=None) -> TeamPlan:
    """Generate an engineering team from a TaskDAG.

    Uses LLM to create task-specific agent roles. Falls back to the fixed
    capability→role mapping when LLM is unavailable.
    """
    layers = dag.layers()

    # Build compact repo summary
    repo_summary = ""
    if repo_profile is not None:
        try:
            parts = []
            if getattr(repo_profile, "languages", []):
                parts.append(f"Languages: {', '.join(repo_profile.languages[:3])}")
            if getattr(repo_profile, "frameworks", []):
                parts.append(f"Frameworks: {', '.join(repo_profile.frameworks[:4])}")
            repo_summary = "; ".join(parts)
        except Exception:
            pass

    agents: list[AgentRole] = []

    if user_input:
        raw = _llm_generate_team(dag, user_input, repo_summary)
        if raw:
            parsed = _parse_llm_agents(raw, dag)
            if parsed:
                agents = parsed

    if not agents:
        agents = _generate_fixed_team(dag, layers)

    # Force all agents into Layer 1: strip every inter-agent dependency so all
    # 4 agents start simultaneously. Agents read any files they need from disk;
    # the integrator resolves any ordering concerns at the end.
    for a in agents:
        a.dependencies = []

    # Compute complexity and strategy
    total_turns = dag.total_estimated_turns()
    num_agents = len(agents)
    complexity = min(10.0, total_turns / 50 + num_agents * 0.5)
    parallel_benefit = _compute_parallel_benefit(dag, num_agents)
    parallel_cost = _compute_parallel_cost(dag, num_agents)

    dag_layers = dag.layers()

    if num_agents <= 1:
        strategy = "single"
        reasoning = "Single agent sufficient"
    else:
        # Parallel-first: always use parallel for 2+ agents.
        # The scheduler enforces real dependency ordering via agent layers —
        # "parallel" just means we use ThreadPoolExecutor within each layer.
        # For a fully linear DAG every layer has 1 agent, so parallel adds no
        # overhead but costs nothing either.
        strategy = "parallel"
        reasoning = (
            f"Parallel-first: {num_agents} agents, {len(dag_layers)} layers, "
            f"{parallel_benefit:.1f}x theoretical speedup"
        )

    risk_counts = dag.risk_summary()
    risk_str = ", ".join(f"{k}={v}" for k, v in sorted(risk_counts.items()))

    return TeamPlan(
        agents=agents,
        complexity=round(complexity, 1),
        risk_assessment=risk_str,
        estimated_total_turns=total_turns,
        estimated_total_tokens=total_turns * 2000,
        parallel_benefit=round(parallel_benefit, 2),
        parallel_cost=round(parallel_cost, 2),
        recommended_strategy=strategy,
        reasoning=reasoning,
        layer_count=len(layers),
    )


# ---------------------------------------------------------------------------
# Fixed-type fallback team (original implementation, preserved)
# ---------------------------------------------------------------------------

_ROLE_TEMPLATES: Dict[str, dict] = {
    "planner": {"mission": "Analyze requirements, design architecture, produce an execution plan", "tools": ["search_smart", "grep", "lookup_symbol"], "max_turns": 20},
    "backend specialist": {"mission": "Implement backend services, APIs, database schema, and business logic", "tools": [], "max_turns": 100},
    "frontend specialist": {"mission": "Implement UI components, pages, state management, and styling", "tools": [], "max_turns": 100},
    "database specialist": {"mission": "Design database schema, migrations, queries, and data models", "tools": [], "max_turns": 40},
    "auth specialist": {"mission": "Implement authentication, authorization, session management, and security", "tools": ["search_smart"], "max_turns": 50},
    "payment specialist": {"mission": "Integrate payment provider, implement billing and webhook handling", "tools": ["search_smart"], "max_turns": 60},
    "testing specialist": {"mission": "Write unit tests, integration tests, E2E tests, and verify coverage", "tools": [], "max_turns": 50},
    "devops specialist": {"mission": "Configure Docker, CI/CD pipelines, deployment, and monitoring", "tools": [], "max_turns": 30},
    "documentation specialist": {"mission": "Write clear, comprehensive documentation for all components", "tools": [], "max_turns": 20},
    "security reviewer": {"mission": "Review code for security vulnerabilities and compliance", "tools": ["search_smart", "grep", "lookup_symbol"], "max_turns": 25},
    "integrator": {"mission": "Merge outputs from all agents, resolve conflicts, and produce a working system", "tools": [], "max_turns": 30},
}

_CAP_TO_ROLE: Dict[str, str] = {
    "frontend": "frontend specialist",
    "backend": "backend specialist",
    "database": "database specialist",
    "authentication": "auth specialist",
    "payments": "payment specialist",
    "testing": "testing specialist",
    "docker": "devops specialist",
    "cicd": "devops specialist",
    "deployment": "devops specialist",
    "documentation": "documentation specialist",
    "security_audit": "security reviewer",
    "profiling": "backend specialist",
    "optimization": "backend specialist",
    "migration": "backend specialist",
    "refactoring": "integrator",
    "integration": "integrator",
    "debugging": "planner",
    "implementation": "planner",
}


def _find_role(node: TaskNode) -> str:
    for cap in node.capabilities_required:
        role = _CAP_TO_ROLE.get(cap)
        if role:
            return role
    return "backend specialist"


def _generate_fixed_team(dag: TaskDAG, layers: list) -> list[AgentRole]:
    """Original fixed capability→role mapping used as fallback."""
    agent_map: Dict[str, AgentRole] = {}
    node_owners: Dict[str, str] = {}

    for layer in layers:
        for node in layer:
            role = _find_role(node)
            agent_id = role.lower().replace(" ", "_")
            if agent_id not in agent_map:
                template = _ROLE_TEMPLATES.get(role, {"mission": f"Complete all {role} work", "tools": [], "max_turns": 60})
                agent_map[agent_id] = AgentRole(
                    id=agent_id, role=role,
                    mission=template["mission"],
                    tools=template["tools"],
                    max_turns=template["max_turns"],
                )
            agent = agent_map[agent_id]
            agent.task_node_ids.append(node.id)
            agent.owns.files.extend(node.affected_files)
            agent.owns.symbols.extend(node.affected_symbols)
            agent.owns.directories.extend(node.affected_dirs)
            agent.validation_rules.extend(node.validation)
            if node.rollback_strategy:
                agent.recovery_rules.append(node.rollback_strategy)
            node_owners[node.id] = agent_id

    # Build agent dependency graph from node dependencies, but ONLY add a
    # dependency when the upstream agent's OUTPUT is actually needed (i.e.
    # the upstream produces schema/contracts the downstream consumes).
    # Avoid chaining agents that could run in parallel (e.g. auth + backend
    # both need the database, but they don't depend on each other).
    for agent in agent_map.values():
        direct_upstream_roles: set = set()
        for nid in agent.task_node_ids:
            node = dag.nodes.get(nid)
            if node:
                for dep_nid in node.dependencies:
                    owner = node_owners.get(dep_nid)
                    owner_agent = agent_map.get(owner) if owner else None
                    if owner and owner != agent.id and owner_agent:
                        # Only add dependency if the upstream agent owns FOUNDATION
                        # work (database/schema/auth) that this agent literally needs
                        # to exist before it can start. Skip cross-cutting deps like
                        # testing→backend or devops→testing (they share no live data).
                        upstream_role = owner_agent.role.lower()
                        is_foundation = any(k in upstream_role for k in
                                            ("database", "schema", "auth", "migration"))
                        if is_foundation:
                            direct_upstream_roles.add(owner)
        agent.dependencies = sorted(direct_upstream_roles)

    return list(agent_map.values())


def _compute_parallel_benefit(dag: TaskDAG, num_agents: int) -> float:
    layers = dag.layers()
    if len(layers) <= 1:
        return 1.0
    sequential = dag.total_estimated_turns()
    # Parallel time = sum of max-turns per layer (nodes within a layer run concurrently).
    # BUG FIX: was using sum() which pessimistically adds all node turns in a layer.
    total_parallel_time = sum(
        max(n.estimated_turns for n in layer)
        for layer in layers
    )
    speedup = sequential / max(total_parallel_time, 1)
    # Light coordination penalty: 2% per agent (not 5% — agents share state via outputs)
    coordination = max(0.0, 1.0 - 0.02 * num_agents)
    return speedup * coordination


def _compute_parallel_cost(dag: TaskDAG, num_agents: int) -> float:
    if num_agents <= 1:
        return 1.0
    # Per-agent overhead: context transfer (10%) + result merge (15%) + startup (8%)
    # No quadratic coordination term — agents share state via prior_outputs, not P2P.
    per_agent = 0.10 + 0.15 + 0.08   # = 0.33 per agent
    return 1.0 + per_agent * num_agents * 0.5  # dampened: 5 agents → ~1.83x
