"""Dynamic Team Generator — creates engineering roles from a TaskDAG.

Agent roles are generated by an LLM that reads the actual task nodes,
user intent, and repo profile. This produces roles tailored to the specific
request rather than a fixed set of templates.

Fallback: if LLM is unavailable, _generate_fixed_team() maps capabilities
to the original 11-role template set.
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from typing import Dict, List, Optional

from agent.orchestration.task_dag import TaskDAG, TaskNode


@dataclass
class OwnedScope:
    """Resources an agent exclusively owns during execution."""
    files: List[str] = field(default_factory=list)
    symbols: List[str] = field(default_factory=list)
    directories: List[str] = field(default_factory=list)
    ports: List[int] = field(default_factory=list)


@dataclass
class AgentRole:
    id: str
    role: str
    mission: str
    owns: OwnedScope = field(default_factory=OwnedScope)
    task_node_ids: List[str] = field(default_factory=list)
    dependencies: List[str] = field(default_factory=list)
    validation_rules: List[str] = field(default_factory=list)
    recovery_rules: List[str] = field(default_factory=list)
    tools: List[str] = field(default_factory=list)
    max_turns: int = 80


@dataclass
class TeamPlan:
    agents: List[AgentRole]
    complexity: float
    risk_assessment: str
    estimated_total_turns: int
    estimated_total_tokens: int
    parallel_benefit: float
    parallel_cost: float
    recommended_strategy: str
    reasoning: str
    layer_count: int = 1


# ---------------------------------------------------------------------------
# LLM-generated dynamic team
# ---------------------------------------------------------------------------

_TEAM_SYSTEM = """You are an engineering team architect optimizing for MAXIMUM PARALLELISM.
Given a task DAG, user request, and repository context, generate the minimum set of
specialized engineering agents that can execute the work as fast as possible.

CRITICAL PARALLELISM RULES:
- Agents with NO shared file/data dependencies MUST have empty depends_on [].
- Only add a dependency when agent B literally cannot start without agent A's OUTPUT.
- Database schema MUST exist before auth or backend can use it → auth/backend depend on db.
- Frontend/UI components are INDEPENDENT of backend API implementation → no dependency.
- Tests and docs are INDEPENDENT of each other → no cross-dependency.
- Aim for wide layers (multiple agents with [] depends_on) not tall chains.

Other rules:
- Generate 1-6 agents. Fewer is better — merge related work into one agent.
- id: kebab-case unique identifier
- role: human-readable job title
- mission: specific one-sentence mission for this exact task (not generic)
- owned_dirs: directories this agent writes to — NO overlap between agents
- max_turns: 20-120

BAD (all sequential, no parallelism):
[{"id":"db","depends_on":[]}, {"id":"auth","depends_on":["db"]}, {"id":"api","depends_on":["auth"]}, {"id":"fe","depends_on":["api"]}, {"id":"test","depends_on":["fe"]}]

GOOD (maximum parallelism):
[{"id":"db","depends_on":[]}, {"id":"auth","depends_on":["db"]}, {"id":"api","depends_on":["db"]}, {"id":"frontend","depends_on":[]}, {"id":"tests","depends_on":["db"]}]

Return ONLY a valid JSON array - no prose, no fences."""


def _llm_generate_team(
    dag: TaskDAG,
    user_input: str,
    repo_summary: str,
) -> Optional[List[dict]]:
    """Ask the planner model to generate a dynamic team. Returns raw agent dicts or None."""
    try:
        from agent.llm import _get_client, PLANNER_MODEL

        dag_summary = json.dumps([
            {"id": n.id, "name": n.name, "description": n.description,
             "capabilities": n.capabilities_required, "deps": n.dependencies,
             "dirs": n.affected_dirs}
            for n in dag.nodes.values()
        ], separators=(",", ":"))

        prompt = (
            f"User request: {user_input[:500]}\n\n"
            f"Repository: {repo_summary[:600]}\n\n"
            f"Task DAG: {dag_summary[:1200]}\n\n"
            "Generate the engineering team:"
        )
        try:
            from agent.model_router import TaskRole, pick_model_for_role
            _team_model = pick_model_for_role(TaskRole.PLANNING)
        except Exception:
            _team_model = PLANNER_MODEL
        client = _get_client()
        resp = client.chat.completions.create(
            model=_team_model,
            messages=[
                {"role": "system", "content": _TEAM_SYSTEM},
                {"role": "user", "content": prompt},
            ],
            temperature=0,
            max_tokens=1500,
            timeout=10,
        )
        raw = (resp.choices[0].message.content or "").strip()
        raw = re.sub(r"^```[a-z]*\n?", "", raw).rstrip("`").strip()
        start = raw.find("[")
        end = raw.rfind("]")
        if start < 0 or end <= start:
            return None
        agents = json.loads(raw[start:end + 1])
        if isinstance(agents, list) and agents:
            return agents
    except Exception:
        pass
    return None


def _parse_llm_agents(raw_agents: List[dict], dag: TaskDAG) -> Optional[List[AgentRole]]:
    """Validate and convert raw LLM agent dicts to AgentRole objects."""
    known_node_ids = set(dag.nodes.keys())
    seen_ids: set = set()
    roles: list[AgentRole] = []

    for raw in raw_agents[:8]:
        aid = str(raw.get("id", "")).strip().replace(" ", "-")
        if not aid or aid in seen_ids:
            continue
        seen_ids.add(aid)

        try:
            turns = max(15, min(120, int(raw.get("max_turns", 60))))
        except (TypeError, ValueError):
            turns = 60

        task_ids = [t for t in (raw.get("task_node_ids") or []) if t in known_node_ids]
        deps = [str(d).strip() for d in (raw.get("depends_on") or []) if str(d).strip()]

        owned = OwnedScope(
            directories=list(raw.get("owned_dirs") or []),
            files=list(raw.get("owned_files") or []),
        )

        # Inherit validation/recovery from owned task nodes
        validation: list[str] = []
        recovery: list[str] = []
        for nid in task_ids:
            node = dag.nodes.get(nid)
            if node:
                validation.extend(node.validation)
                if node.rollback_strategy:
                    recovery.append(node.rollback_strategy)

        roles.append(AgentRole(
            id=aid,
            role=str(raw.get("role", aid)),
            mission=str(raw.get("mission", f"Complete {aid} tasks")),
            owns=owned,
            task_node_ids=task_ids,
            dependencies=deps,
            validation_rules=validation,
            recovery_rules=recovery,
            max_turns=turns,
        ))

    if not roles:
        return None

    # Validate deps reference known agent ids
    valid_aids = {r.id for r in roles}
    for r in roles:
        r.dependencies = [d for d in r.dependencies if d in valid_aids]

    return roles


# ---------------------------------------------------------------------------
# Public builder
# ---------------------------------------------------------------------------

def generate_team(dag: TaskDAG, user_input: str = "", repo_profile=None) -> TeamPlan:
    """Generate an engineering team from a TaskDAG.

    Uses LLM to create task-specific agent roles. Falls back to the fixed
    capability→role mapping when LLM is unavailable.
    """
    layers = dag.layers()

    # Build compact repo summary
    repo_summary = ""
    if repo_profile is not None:
        try:
            parts = []
            if getattr(repo_profile, "languages", []):
                parts.append(f"Languages: {', '.join(repo_profile.languages[:3])}")
            if getattr(repo_profile, "frameworks", []):
                parts.append(f"Frameworks: {', '.join(repo_profile.frameworks[:4])}")
            repo_summary = "; ".join(parts)
        except Exception:
            pass

    agents: list[AgentRole] = []

    if user_input:
        raw = _llm_generate_team(dag, user_input, repo_summary)
        if raw:
            parsed = _parse_llm_agents(raw, dag)
            if parsed:
                agents = parsed

    if not agents:
        agents = _generate_fixed_team(dag, layers)

    # Compute complexity and strategy
    total_turns = dag.total_estimated_turns()
    num_agents = len(agents)
    complexity = min(10.0, total_turns / 50 + num_agents * 0.5)
    parallel_benefit = _compute_parallel_benefit(dag, num_agents)
    parallel_cost = _compute_parallel_cost(dag, num_agents)

    dag_layers = dag.layers()
    has_parallel_layers = any(len(layer) > 1 for layer in dag_layers)

    if num_agents <= 1:
        strategy = "single"
        reasoning = "Single agent sufficient"
    else:
        # Parallel-first: always use parallel for 2+ agents.
        # The scheduler enforces real dependency ordering via agent layers —
        # "parallel" just means we use ThreadPoolExecutor within each layer.
        # For a fully linear DAG every layer has 1 agent, so parallel adds no
        # overhead but costs nothing either.
        strategy = "parallel"
        reasoning = (
            f"Parallel-first: {num_agents} agents, {len(dag_layers)} layers, "
            f"{parallel_benefit:.1f}x theoretical speedup"
        )

    risk_counts = dag.risk_summary()
    risk_str = ", ".join(f"{k}={v}" for k, v in sorted(risk_counts.items()))

    return TeamPlan(
        agents=agents,
        complexity=round(complexity, 1),
        risk_assessment=risk_str,
        estimated_total_turns=total_turns,
        estimated_total_tokens=total_turns * 2000,
        parallel_benefit=round(parallel_benefit, 2),
        parallel_cost=round(parallel_cost, 2),
        recommended_strategy=strategy,
        reasoning=reasoning,
        layer_count=len(layers),
    )


# ---------------------------------------------------------------------------
# Fixed-type fallback team (original implementation, preserved)
# ---------------------------------------------------------------------------

_ROLE_TEMPLATES: Dict[str, dict] = {
    "planner": {"mission": "Analyze requirements, design architecture, produce an execution plan", "tools": ["search_smart", "grep", "lookup_symbol"], "max_turns": 20},
    "backend specialist": {"mission": "Implement backend services, APIs, database schema, and business logic", "tools": [], "max_turns": 100},
    "frontend specialist": {"mission": "Implement UI components, pages, state management, and styling", "tools": [], "max_turns": 100},
    "database specialist": {"mission": "Design database schema, migrations, queries, and data models", "tools": [], "max_turns": 40},
    "auth specialist": {"mission": "Implement authentication, authorization, session management, and security", "tools": ["search_smart"], "max_turns": 50},
    "payment specialist": {"mission": "Integrate payment provider, implement billing and webhook handling", "tools": ["search_smart"], "max_turns": 60},
    "testing specialist": {"mission": "Write unit tests, integration tests, E2E tests, and verify coverage", "tools": [], "max_turns": 50},
    "devops specialist": {"mission": "Configure Docker, CI/CD pipelines, deployment, and monitoring", "tools": [], "max_turns": 30},
    "documentation specialist": {"mission": "Write clear, comprehensive documentation for all components", "tools": [], "max_turns": 20},
    "security reviewer": {"mission": "Review code for security vulnerabilities and compliance", "tools": ["search_smart", "grep", "lookup_symbol"], "max_turns": 25},
    "integrator": {"mission": "Merge outputs from all agents, resolve conflicts, and produce a working system", "tools": [], "max_turns": 30},
}

_CAP_TO_ROLE: Dict[str, str] = {
    "database": "database specialist",
    "authentication": "auth specialist",
    "payments": "payment specialist",
    "testing": "testing specialist",
    "docker": "devops specialist",
    "cicd": "devops specialist",
    "deployment": "devops specialist",
    "documentation": "documentation specialist",
    "security_audit": "security reviewer",
    "profiling": "backend specialist",
    "optimization": "backend specialist",
    "migration": "backend specialist",
    "refactoring": "integrator",
    "integration": "integrator",
    "debugging": "planner",
    "implementation": "planner",
}


def _find_role(node: TaskNode) -> str:
    for cap in node.capabilities_required:
        role = _CAP_TO_ROLE.get(cap)
        if role:
            return role
    return "backend specialist"


def _generate_fixed_team(dag: TaskDAG, layers: list) -> list[AgentRole]:
    """Original fixed capability→role mapping used as fallback."""
    agent_map: Dict[str, AgentRole] = {}
    node_owners: Dict[str, str] = {}

    for layer in layers:
        for node in layer:
            role = _find_role(node)
            agent_id = role.lower().replace(" ", "_")
            if agent_id not in agent_map:
                template = _ROLE_TEMPLATES.get(role, {"mission": f"Complete all {role} work", "tools": [], "max_turns": 60})
                agent_map[agent_id] = AgentRole(
                    id=agent_id, role=role,
                    mission=template["mission"],
                    tools=template["tools"],
                    max_turns=template["max_turns"],
                )
            agent = agent_map[agent_id]
            agent.task_node_ids.append(node.id)
            agent.owns.files.extend(node.affected_files)
            agent.owns.symbols.extend(node.affected_symbols)
            agent.owns.directories.extend(node.affected_dirs)
            agent.validation_rules.extend(node.validation)
            if node.rollback_strategy:
                agent.recovery_rules.append(node.rollback_strategy)
            node_owners[node.id] = agent_id

    # Build agent dependency graph from node dependencies, but ONLY add a
    # dependency when the upstream agent's OUTPUT is actually needed (i.e.
    # the upstream produces schema/contracts the downstream consumes).
    # Avoid chaining agents that could run in parallel (e.g. auth + backend
    # both need the database, but they don't depend on each other).
    for agent in agent_map.values():
        direct_upstream_roles: set = set()
        for nid in agent.task_node_ids:
            node = dag.nodes.get(nid)
            if node:
                for dep_nid in node.dependencies:
                    owner = node_owners.get(dep_nid)
                    owner_agent = agent_map.get(owner) if owner else None
                    if owner and owner != agent.id and owner_agent:
                        # Only add dependency if the upstream agent owns FOUNDATION
                        # work (database/schema/auth) that this agent literally needs
                        # to exist before it can start. Skip cross-cutting deps like
                        # testing→backend or devops→testing (they share no live data).
                        upstream_role = owner_agent.role.lower()
                        is_foundation = any(k in upstream_role for k in
                                            ("database", "schema", "auth", "migration"))
                        if is_foundation:
                            direct_upstream_roles.add(owner)
        agent.dependencies = sorted(direct_upstream_roles)

    return list(agent_map.values())


def _compute_parallel_benefit(dag: TaskDAG, num_agents: int) -> float:
    layers = dag.layers()
    if len(layers) <= 1:
        return 1.0
    sequential = dag.total_estimated_turns()
    # Parallel time = sum of max-turns per layer (nodes within a layer run concurrently).
    # BUG FIX: was using sum() which pessimistically adds all node turns in a layer.
    total_parallel_time = sum(
        max(n.estimated_turns for n in layer)
        for layer in layers
    )
    speedup = sequential / max(total_parallel_time, 1)
    # Light coordination penalty: 2% per agent (not 5% — agents share state via outputs)
    coordination = max(0.0, 1.0 - 0.02 * num_agents)
    return speedup * coordination


def _compute_parallel_cost(dag: TaskDAG, num_agents: int) -> float:
    if num_agents <= 1:
        return 1.0
    # Per-agent overhead: context transfer (10%) + result merge (15%) + startup (8%)
    # No quadratic coordination term — agents share state via prior_outputs, not P2P.
    per_agent = 0.10 + 0.15 + 0.08   # = 0.33 per agent
    return 1.0 + per_agent * num_agents * 0.5  # dampened: 5 agents → ~1.83x
