import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        bg:          "#0B0B0C",
        surface:     "#111214",
        panel:       "#151618",
        "panel-hover": "#1A1B1E",
        card:        "#111214",
        "card-hover":"#1A1B1E",

        border:      "#25272B",
        "border-soft":"#1E1F23",
        "border-bright":"#3A3D43",

        text:        "#F5F5F5",
        muted:       "#8A8F98",
        dim:         "#5A5F67",
        faint:       "#3A3D43",

        accent:      "#60A5FA",
        "accent-fg": "#0B0B0C",
        "accent-muted": "#60A5FA18",
        success:     "#4ADE80",
        "success-muted": "#4ADE8018",
        warning:     "#FACC15",
        "warning-muted": "#FACC1518",
        danger:      "#F87171",
        "danger-muted": "#F8717118",

        brand:       "#F5F5F5",
      },
      borderRadius: {
        xs:    "2px",
        sm:    "3px",
        md:    "4px",
        lg:    "6px",
        xl:    "8px",
      },
      fontFamily: {
        sans: ["Inter", "SF Pro Display", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "Fira Code", "Cascadia Code", "SF Mono", "Menlo", "monospace"],
      },
      fontSize: {
        "2xs": ["10px", { lineHeight: "14px" }],
        xs:    ["11px", { lineHeight: "16px" }],
        sm:    ["12px", { lineHeight: "18px" }],
        base:  ["13px", { lineHeight: "20px" }],
        md:    ["14px", { lineHeight: "22px" }],
        lg:    ["16px", { lineHeight: "24px" }],
        xl:    ["18px", { lineHeight: "28px" }],
      },
      spacing: {
        "0.5": "2px",
        "1":   "4px",
        "1.5": "6px",
        "2":   "8px",
        "2.5": "10px",
        "3":   "12px",
        "4":   "16px",
        "5":   "20px",
        "6":   "24px",
        "8":   "32px",
        "10":  "40px",
        "12":  "48px",
      },
      keyframes: {
        "fade-in":     { "0%": { opacity: "0" }, "100%": { opacity: "1" } },
        "slide-up":    { "0%": { opacity: "0", transform: "translateY(6px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "slide-down":  { "0%": { opacity: "0", transform: "translateY(-6px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "pulse-dot":   { "0%, 100%": { opacity: "1" }, "50%": { opacity: "0.3" } },
        "spin-slow":   { "0%": { transform: "rotate(0deg)" }, "100%": { transform: "rotate(360deg)" } },
        "shimmer":     { "0%": { backgroundPosition: "-200% 0" }, "100%": { backgroundPosition: "200% 0" } },
        "stream":      { "0%": { opacity: "0.4" }, "100%": { opacity: "1" } },
        "scale-check": { "0%": { transform: "scale(0)", opacity: "0" }, "50%": { transform: "scale(1.2)" }, "100%": { transform: "scale(1)", opacity: "1" } },
      },
      animation: {
        "fade-in":      "fade-in 120ms ease-out",
        "slide-up":     "slide-up 120ms cubic-bezier(0.16, 1, 0.3, 1)",
        "slide-down":   "slide-down 120ms cubic-bezier(0.16, 1, 0.3, 1)",
        "pulse-dot":    "pulse-dot 1.4s ease-in-out infinite",
        "spin-slow":    "spin-slow 1s linear infinite",
        "shimmer":      "shimmer 1.5s infinite linear",
        "stream":       "stream 180ms ease-out",
        "scale-check":  "scale-check 200ms cubic-bezier(0.16, 1, 0.3, 1)",
      },
      transitionDuration: {
        "100": "100ms",
        "120": "120ms",
        "150": "150ms",
        "180": "180ms",
        "200": "200ms",
      },
      boxShadow: {
        "sm":    "0 1px 2px rgba(0,0,0,0.3)",
        "md":    "0 3px 8px rgba(0,0,0,0.35)",
        "lg":    "0 8px 24px rgba(0,0,0,0.4)",
        "panel": "0 0 0 1px #25272B",
        "modal": "0 0 0 1px #25272B, 0 16px 48px rgba(0,0,0,0.5)",
        "inset": "inset 0 -1px 0 #1E1F23",
      },
    },
  },
  plugins: [],
};

export default config;
